version: "3.8"

services:
  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - banksystemsimulation-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/BankSystemSimulation
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - postgres
    volumes:
      - ~/.m2:/root/.m2

  postgres:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - banksystemsimulation-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: BankSystemSimulation
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  banksystemsimulation-net:

volumes:
  pgdata:
 